# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bio-ConnectDots
version:      1.0.1
version_from: lib/Bio/ConnectDots/ConnectDots.pm
installdirs:  site
requires:
    Carp:                          
    Class::AutoClass:              0.09
    DBD::Pg:                       
    File::Path:                    
    Getopt::Long:                  
    Test::More:                    
    Test::XML::XPath:              
    Text::Abbrev:                  

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
